Add test to restore transactions behavior.
dbt-labs/dbt-postgres pull request #24
Opened 2024-02-27 06:56 UTC by VersusFacit

resolves #23 

Added a test. 

### Checklist

- [X] I have read [the contributing guide](https://github.com/dbt-labs/dbt-postgres/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [X] I have run this code in development and it appears to resolve the stated issue
- [X] This PR includes tests, or tests are not required/relevant for this PR
- [X] This PR has no interface changes (e.g. macros, cli, logs, json artifacts, config files, adapter interface, etc) or this PR has already received feedback and approval from Product or DX

2024-02-27 14:49 UTC, mikealfare commented
All the test failures look related to (https://github.com/dbt-labs/dbt-postgres/pull/21). Once that PR is merged and this is updated from `main`, it should pass.

2024-02-28 18:28 UTC, VersusFacit commented
Still getting hurt by dependency collisions. Is there something specific to this repo I can fix?

2024-03-20 17:51 UTC, mikealfare requested changes

2024-03-20 17:51 UTC, mikealfare commented on pyproject.toml
> +    "dbt-adapters @ git+https://github.com/dbt-labs/dbt-adapters.git@ADAP-108/fix_renamed_relations_for_1.8",
Adding a blocking change to make sure we don't accidentally merge this.

2024-03-21 14:27 UTC, mikealfare approved these changes

2024-03-21 14:44 UTC, merged